[server]
port = 8501
headless = false
runOnSave = true
folderWatchBlacklist = [".scrapy"]

[client]
toolbarMode = "minimal"

[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[ui]
hideTopBar = true

# Eigene Einstellungen kannst du unterhalb dieser Zeile einfügen.


[theme]
primaryColor="#7D2020"
backgroundColor="#F4F2EE"
secondaryBackgroundColor="#FAEAEA"
textColor="#7D2020"
font="sans serif"
